name: Deploy via SFTP

on:
  push:
    branches:
      - main  # O la rama que quieras desplegar

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List files in workspace
        run: ls -laR # Lista recursivamente para ver contenido de assets y data también

      - name: Deploy files to OVH via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          sftp: true
          local-dir: ./ # O la subcarpeta si tienes un build, ej: ./dist/
          server-dir: /home/roblesx-votomut/
          log-level: verbose